platform :ios, '9.0'

target 'PolyvRNCloudClassDemo' do
  use_frameworks!

  # 保利威 多场景 SDK
  pod 'PLVLiveScenesSDK', '1.3.0'
  
  # 保利威 UI源码 需依赖的库
  pod 'SDWebImage', '4.4.0'
  pod 'MJRefresh', '~> 3.5.0'

  # 执行 npm install 命令之后，有可能会自动生成下面这两行配置，需要把这两行配置删掉或者注释掉
  # pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  # pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end
